language: java

script: mvn clean install -DskipTests=false -Dmaven.javadoc.skip=true -B -V -U

jdk:
  - oraclejdk8

notifications:
  recipients:
    - andreswinck@gmail.com
  email:
    on_success: change
    on_failure: always